### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/comfig-fortress#4]
https://github.com/mastercomfig/comfig-fortress/blob/0b87ea40e94be6bd64fe05b3925a0b63237b0c32/LICENSE#L3

Shouldn't the license say "mastercoms"? All other software have mastercoms in license and not mastercomfig.

**Comment by mastercoms** [comment]
Yes, I think it defaulted to mastercomfig because it was created in the organization.

**Comment by micwoj92** [comment]
XD
